// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { GeohashTree } from '../../osm/parser/geohash-tree';


export class DataTable {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):DataTable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDataTable(bb:flatbuffers.ByteBuffer, obj?:DataTable):DataTable {
  return (obj || new DataTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDataTable(bb:flatbuffers.ByteBuffer, obj?:DataTable):DataTable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DataTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

geohashHighwayNodes(obj?:GeohashTree):GeohashTree|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new GeohashTree()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startDataTable(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addGeohashHighwayNodes(builder:flatbuffers.Builder, geohashHighwayNodesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, geohashHighwayNodesOffset, 0);
}

static endDataTable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishDataTableBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedDataTableBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createDataTable(builder:flatbuffers.Builder, geohashHighwayNodesOffset:flatbuffers.Offset):flatbuffers.Offset {
  DataTable.startDataTable(builder);
  DataTable.addGeohashHighwayNodes(builder, geohashHighwayNodesOffset);
  return DataTable.endDataTable(builder);
}
}
