// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { GeohashTreeBox } from '../../osm/parser/geohash-tree-box';


export class GeohashTree {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):GeohashTree {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGeohashTree(bb:flatbuffers.ByteBuffer, obj?:GeohashTree):GeohashTree {
  return (obj || new GeohashTree()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGeohashTree(bb:flatbuffers.ByteBuffer, obj?:GeohashTree):GeohashTree {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GeohashTree()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

precision():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
}

data(index: number, obj?:GeohashTreeBox):GeohashTreeBox|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new GeohashTreeBox()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

dataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGeohashTree(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPrecision(builder:flatbuffers.Builder, precision:number) {
  builder.addFieldInt8(0, precision, 0);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
}

static createDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGeohashTree(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGeohashTree(builder:flatbuffers.Builder, precision:number, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  GeohashTree.startGeohashTree(builder);
  GeohashTree.addPrecision(builder, precision);
  GeohashTree.addData(builder, dataOffset);
  return GeohashTree.endGeohashTree(builder);
}
}
