// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { OsmNodesConnectionData } from '../../osm/parser/osm-nodes-connection-data';


export class OsmNodesConnection {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):OsmNodesConnection {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOsmNodesConnection(bb:flatbuffers.ByteBuffer, obj?:OsmNodesConnection):OsmNodesConnection {
  return (obj || new OsmNodesConnection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOsmNodesConnection(bb:flatbuffers.ByteBuffer, obj?:OsmNodesConnection):OsmNodesConnection {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OsmNodesConnection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nodeId():string|null
nodeId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
nodeId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

data(obj?:OsmNodesConnectionData):OsmNodesConnectionData|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new OsmNodesConnectionData()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startOsmNodesConnection(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addNodeId(builder:flatbuffers.Builder, nodeIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nodeIdOffset, 0);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
}

static endOsmNodesConnection(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
